// async function getAllUser(){
// try { //try and catch is the method use to catch the error because in async await function can not resolve the error
//     const data= await fetch("https://api.github.com/users")   //fetch is needeed url as a parameter ,it will give us data from that url
//     const data2=await data.json()   //json is typr here to convert the data at object/json format because it is in string format
//     console.log(data2);
    
    
   
// } catch (error) {
//     console.log("E:",error);
    
// }
    
// }
// getAllUser()



//.then  method 


// fetch("https://api.github.com/users")
// .then((response)=>{
//     return response.json()
// })
// .then((data)=>{
//     console.log(data);
    
// })
// .catch((error)=>{
//     console.log(error);
    
// })
